### ISSUE TITLE
client var overrides Chef::Client in Chef Automate delivery-cmd

### ISSUE THREAD

**Issue by mattlqx** [KierranM/ec2-tags-ohai-plugin#3]
This is a really odd specific case, but I'll do my best to explain it. I run the `ec2-tags-ohai-plugin` on my hosts. I run Chef Automate which has "runner" processes that run on hosts and do the work for Workflow to build and deploy applications. The runners are installed by the main cli utility `automate-ctl`. Among other things, it installs ChefDK on to the node with a desired version and a `delivery-cmd` script that handles getting instructions from the main Chef Automate server.

`delivery-cmd` contains the following code near the top of the main block:
```
Chef::Config.from_file(Chef::Config.platform_specific_path("/etc/chef/client.rb"))
client = Chef::Client.new
client.run_ohai
client.node_name
```

When running with ChefDK 1.4.3, everything works as expected. But with ChefDK 1.5.0 and higher, running it yields this:
```
/usr/local/bin/delivery-cmd:103:in `<main>': undefined method `node_name' for #<Aws::EC2::Client> (NoMethodError)
```

Which instantly led me to look at this plugin because the prior line is `client.run_ohai`. I put a pry breakpoint in /etc/chef/ohai/plugins/ec2-tags.rb and after some debugging, it seems that with 1.4.3 the `ec2-tags-ohai-plugin` isn't loaded, but with 1.5.0 it is and that's where things get weird. When the ohai plugin is loaded, apparently a local variable `client` already exists in the plugin's scope and it's an instance of `Chef::Client`. When the `ec2-tags-ohai-plugin` is executed, the `client` variable is overridden with an instance of `Aws::EC2::Client` which persists after the plugin execution is complete in the main scope of the script and causes it to fail.

Here's some debugger output:
```
#  /usr/local/bin/delivery-cmd 

Frame number: 0/11

From: /etc/chef/ohai/plugins/ec2-tags.rb @ line 14 :

     9:   collect_data do
    10:     begin
    11:       require 'aws-sdk-core'
    12:       binding.pry
    13: 
 => 14:       client = Aws::EC2::Client.new region: ec2['placement_availability_zone'][0...-1]
    15:       resp = client.describe_tags(
    16:         filters: [
    17:           {
    18:             name: 'resource-id',
    19:             values: [

[1] pry(#<Ohai::NamedPlugin::EC2Tags>)> ls
Ohai::Mixin::Command#methods: run_command_backend  run_command_unix  run_command_windows
Ohai::Mixin::SecondsToHuman#methods: seconds_to_human
Ohai::Util::FileHelper#methods: which
Ohai::DSL::Plugin#methods: []  []=  attribute?  data  each  from  from_with_regex  get_attribute  has_key?  has_run?  hint?  method_missing  reset!  run  safe_run  set  set_attribute
Ohai::DSL::Plugin::VersionVII#methods: configuration  dependencies  name  provides  require_plugin  run_plugin  source  version
instance variables: @data  @has_run  @source  @version
locals: 
  _   _dir_  _file_  _out_  builder_auth_headers  chef_stacktrace_file  client  command_line     custom_cert_filepath  elapsed_time  http_proxy   job_data  path             raw_json  rest    start_datetime  workspace_bin 
  __  _ex_   _in_    _pry_  change_file           cli_env               cmd     compliance_json  e                     end_datetime  https_proxy  no_proxy  path_compliance  resp      server  streamy         workspace_root
[2] pry(#<Ohai::NamedPlugin::EC2Tags>)> client
=> #<Chef::Client:0x0000000324d620 ...>
[4] pry(#<Ohai::NamedPlugin::EC2Tags>)> next

From: /etc/chef/ohai/plugins/ec2-tags.rb @ line 15 :

    10:     begin
    11:       require 'aws-sdk-core'
    12:       binding.pry
    13: 
    14:       client = Aws::EC2::Client.new region: ec2['placement_availability_zone'][0...-1]
 => 15:       resp = client.describe_tags(
    16:         filters: [
    17:           {
    18:             name: 'resource-id',
    19:             values: [
    20:               ec2['instance_id']

[4] pry(#<Ohai::NamedPlugin::EC2Tags>):1> client
=> #<Aws::EC2::Client>
```

The quick workaround is to just rename the `client` variable in the plugin to something that doesn't collide like `ec2_client` and I'll submit a pull request for that. I'm not really sure where the problem is exactly upstream to report that. Any thoughts are appreciated.

**Comment by KierranM** [comment]
PR merged and released, thanks for that. Can't say I'm sure where the right place to raise that issue would be either :/
