### ISSUE TITLE
Plugin doesn't work with ruby aws-sdk version 3.0.0

### ISSUE THREAD

**Issue by ghTravis** [KierranM/ec2-tags-ohai-plugin#5]
Today we had an issue where the plugin wasn't populating the node['ec2']['tags'] hash. We tracked it down to an update to the ruby aws-sdk that happened today version 3.0.0. It seems that something is wrong either with their update or they have changed some core functionality with describing tags.

They may have realized their error because they seem to have taken the release off of their github releases page, but the version still exists in the gem repo for ubuntu.

We ended up having to pin the version as of now at 2.10.35. As of right now, I'm unsure what the issue is because the plugin installation doesn't throw any errors when it compiles and installs the sdk for the first time.

**Comment by Fodoj** [comment]
@ghTravis how did you pin the version?

**Comment by ghTravis** [comment]
Set an attribute node['aws']['aws_sdk_version'] = '2.10.35' preferably in a role as an attribute override

**Comment by Fodoj** [comment]
Ok. I fixed it by changing `require 'aws-sdk-core'` to `require 'aws-sdk'`. Seems like new AWS SDK version moved ec2 module to different place.

**Comment by ghTravis** [comment]
The pull request by tpath changes the requires statement to aws-sdk-ec2. Might be more efficient? Not entirely sure how ruby handles importing libraries and memory footprint etc.

**Comment by tpath** [comment]
Yes, it would be make to code footprint smaller, by just installing and using aws-sdk-ec2. I tested it on my environments and it seems to work fine.

**Comment by ghTravis** [comment]
@tpath does your change work with 2.10.35?

**Comment by tpath** [comment]
No, it will only work from version 3 upwards since AWS introduced this kind of modularisation only from that version onwards (see https://aws.amazon.com/blogs/developer/announcing-the-modularized-aws-sdk-for-ruby-version-3/)

**Comment by ghTravis** [comment]
Not sure how the plugin operates with the new aws-sdk but this issue seems to be shedding some light on the problem: https://github.com/aws/aws-sdk-ruby/issues/1581

**Comment by awood45** [comment]
You shouldn't see the binary conflict issue anymore with `3.0.1`, please reopen that issue if you do.

@tpath is correct that modularization is new to major version 3, and the recommendation of reducing your dependencies to service-specific gems is a good one. We have an [upgrading guide](https://github.com/aws/aws-sdk-ruby/blob/code-generation/V3_UPGRADING_GUIDE.md) which should also help.

**Comment by KierranM** [comment]
#6 has been released which resolves this issue.
