### ISSUE TITLE
Incompatible with aws cookbook

### ISSUE THREAD

**Issue by aprice** [KierranM/ec2-tags-ohai-plugin#7]
If I run the current version of ec2-tags-ohai-plugin (0.2.4) and try to use the current version of the aws cookbook, I get the following error:

`ERROR: Unable to activate aws-sdk-resources-2.10.61, because aws-sdk-core-3.6.0 conflicts with aws-sdk-core (= 2.10.61)`

Because the aws cookbook isn't run as a recipe (it just exposes resource providers), there is no way to control when it executes as far as I can tell.

The aws cookbook includes:

`gem 'aws-sdk', '~> 2'`

But the ec2-tags-ohai-plugin cookbook has `gem` entry in metadata; it just uses the `chef_gem` resource to install it in the recipe, with no version pin.

Adding `gem 'aws-sdk', '~> 2'` to my the metadata  of my cookbook that calls ec2-tags-ohai-plugin seems to fix the issue, as does pinning ec2-tags-ohai-plugin to v0.2.3. If I was calling this cookbook directly in the runlist and then trying to use the aws resources in another cookbook, I don't know how this could be worked around.

Maybe adding an attribute to allow pinning the version of the gem installed using the chef_gem resource would fix the issue?

**Comment by rberger** [comment]
Yep breaks it for me too if I'm using the aws cookbook. If I pin `ec2-tags-ohai-plugin`  to `0.2.3` things work again.

**Comment by KierranM** [comment]
The latest AWS cookbook specifies `gem 'aws-sdk', '>= 2', '< 4.0'`. Given that the last change added support for aws-sdk V3 (and therefore dropped V2 support) I think pinning back to 0.2.3 is the only option here. I had a quick look at if it would be possible to make it compatible with both V2 and V3, but it seems like significant effort for little gain. Given this is now being used by other people, the next time I make a change I'll bump to 1.0.0 and start following SemVer properly
